language: go

go:
    - 1.4.2

install:
    - go get github.com/onsi/ginkgo
    - go get github.com/onsi/gomega
    - go get github.com/sclevine/agouti
    - go get github.com/PuerkitoBio/goquery

script: go test -v github.com/caledhwa/gongeal/test/acceptance -run ^TestAcceptance$